'use client';

import React, { useState, useEffect, useRef } from 'react';
import { CardProps } from '../../types';
import { getAllTags } from '../../lib/api';
import MultiImageUploader from './MultiImageUploader';
import SocialCopyModal from '../cards/SocialCopyModal';

// Type labels for display
const TYPE_LABELS = {
  'image': 'Image',
  'social': 'Post',
  'reel': 'Reel'
};


interface CardFormProps {
  initialData?: CardProps;
  initialCardType?: string;
  onSubmit: (formData: FormData) => Promise<void>;
  onCancel: () => void;
  availableTags?: string[];
  isSubmitting?: boolean;
}

const CardFormNew: React.FC<CardFormProps> = ({ 
  initialData, 
  initialCardType = 'image', 
  onSubmit, 
  onCancel, 
  availableTags = [],
  isSubmitting = false 
}) => {
  // Check if we have dropped image data from an ImageCard
  const hasDroppedImageData = typeof window !== 'undefined' && window.imageCardFormData;
  
  // Handle dropped image data if it exists
  useEffect(() => {
    if (hasDroppedImageData && initialData?.type === 'image') {
      
      // Get formdata from window object
      const imageFormData = window.imageCardFormData;
      
      if (imageFormData) {
        // The rest of the form submission will be handled automatically
        // Just need to update the UI to show that we're processing the dropped image
        setUploadedFiles(prev => ({
          ...prev,
          preview: imageFormData.get('preview') as File,
          download: imageFormData.get('preview') as File,
        }));
        
        // Since we're updating the image, mark the preview for regeneration
        setIsPreviewAutogenerated(true);
      }
    }
  }, [hasDroppedImageData, initialData]);

  // Card type is now stored in state so it can be changed before creation
  const [type, setType] = useState<"image" | "social" | "reel">(
    (initialData?.type as "image" | "social" | "reel") || 
    (initialCardType === 'all' ? 'image' : initialCardType as "image" | "social" | "reel")
  );
  const [description, setDescription] = useState(initialData?.description || '');
  
  // For handling date input with proper formatting
  // Format initial date in MM/DD/YYYY format
  const formatDateMMDDYYYY = (dateStr: string | Date): string => {
    const date = new Date(dateStr);
    if (isNaN(date.getTime())) {
      return ''; // Invalid date
    }
    const month = (date.getMonth() + 1).toString().padStart(2, '0');
    const day = date.getDate().toString().padStart(2, '0');
    const year = date.getFullYear();
    return `${month}/${day}/${year}`;
  };

  // Initial date value formatted as MM/DD/YYYY
  const initialFormattedDate = initialData?.fileMetadata?.date
    ? formatDateMMDDYYYY(initialData.fileMetadata.date)
    : formatDateMMDDYYYY(new Date());

  const [date, setDate] = useState<string>(initialFormattedDate);
  // Track if date has been modified to handle Enter key behavior
  const [isDateModified, setIsDateModified] = useState<boolean>(false);
  
  
  // Helper to parse and format date input
  const parseAndFormatDate = (inputDate: string): string => {
    try {
      // Handle various date formats (MM/DD/YYYY, YYYY-MM-DD, MM-DD-YYYY, etc.)
      const rawInput = inputDate.trim();
      
      // Direct 4-digit year input - handle specially
      if (/^\d{4}$/.test(rawInput)) {
        const year = parseInt(rawInput, 10);
        if (year >= 1900 && year <= 2100) {
          // Use current month and day with specified year
          const today = new Date();
          const month = today.getMonth() + 1;
          const day = today.getDate();
          return `${month.toString().padStart(2, '0')}/${day.toString().padStart(2, '0')}/${year}`;
        } else {
          // Invalid year, return today's date
          return formatDateMMDDYYYY(new Date());
        }
      }
      
      // Try to parse various formats
      let dateObj;
      
      // Check if it already matches our target format (MM/DD/YYYY)
      if (/^\d{1,2}\/\d{1,2}\/\d{4}$/.test(rawInput)) {
        const [month, day, year] = rawInput.split('/').map(part => parseInt(part, 10));
        dateObj = new Date(year, month - 1, day);
      }
      // ISO format (YYYY-MM-DD)
      else if (/^\d{4}-\d{1,2}-\d{1,2}$/.test(rawInput)) {
        dateObj = new Date(rawInput);
      }
      // MM-DD-YYYY
      else if (/^\d{1,2}-\d{1,2}-\d{4}$/.test(rawInput)) {
        const [month, day, year] = rawInput.split('-').map(part => parseInt(part, 10));
        dateObj = new Date(year, month - 1, day);
      }
      // All other formats - try JavaScript Date parsing
      else {
        dateObj = new Date(rawInput);
      }
      
      // Validate the parsed date
      if (!isNaN(dateObj.getTime())) {
        const year = dateObj.getFullYear();
        // Validate year range
        if (year >= 1900 && year <= 2100) {
          // Format as MM/DD/YYYY
          const month = (dateObj.getMonth() + 1).toString().padStart(2, '0');
          const day = dateObj.getDate().toString().padStart(2, '0');
          return `${month}/${day}/${year}`;
        }
      }
      
      // If all validation fails, return today's date
      return formatDateMMDDYYYY(new Date());
    } catch (error) {
      console.error("Error parsing date:", error);
      // If parsing fails, return today's date
      return formatDateMMDDYYYY(new Date());
    }
  };
  const [tags, setTags] = useState<string[]>(initialData?.tags || []);
  const [newTag, setNewTag] = useState('');
  const [uploadedFiles, setUploadedFiles] = useState<Record<string, File | null | boolean | File[]>>({
    preview: null,
    download: null,
    movie: null,
    transcript: null,
    remove_preview: false,
    imageSequence: [],
  });
  
  // Track existing image sequence separately since we don't want to upload it again
  // Keep the original list to restore on cancel
  const originalImageSequence = useRef<string[]>(initialData?.imageSequence || []);
  const [existingImageSequence, setExistingImageSequence] = useState<string[]>(initialData?.imageSequence || []);
  const [errors, setErrors] = useState<Record<string, string>>({});
  
  // Flag to indicate if the preview is autogenerated
  const [isPreviewAutogenerated, setIsPreviewAutogenerated] = useState<boolean>(false);
  
  // Social copy state
  const [instagramCopy, setInstagramCopy] = useState(initialData?.instagramCopy || '');
  const [facebookCopy, setFacebookCopy] = useState(initialData?.facebookCopy || '');
  const [isSocialCopyModalOpen, setIsSocialCopyModalOpen] = useState(false);
  const [activeSocialCopyTab, setActiveSocialCopyTab] = useState<'instagram' | 'facebook'>('instagram');

  // For tag autocomplete
  const [allAvailableTags, setAllAvailableTags] = useState<string[]>(availableTags);
  const [filteredTags, setFilteredTags] = useState<string[]>([]);
  const [isTagsDropdownOpen, setIsTagsDropdownOpen] = useState(false);
  
  // Flag to track if we should automatically open the social copy editor
  const autoOpenSocialCopyRef = useRef<boolean>(false);
  const autoOpenSocialCopyTabRef = useRef<'instagram' | 'facebook'>('instagram');
  
  // Listen for custom event to open social copy editor with specific tab
  useEffect(() => {
    const handleOpenSocialCopyEditor = (e: CustomEvent) => {
      // Only handle events for this card
      if (initialData?.id === e.detail.cardId) {
        // Instead of immediately opening the modal, set the flag to open it after the component mounts
        autoOpenSocialCopyRef.current = true;
        if (e.detail.tab === 'instagram' || e.detail.tab === 'facebook') {
          autoOpenSocialCopyTabRef.current = e.detail.tab;
          setActiveSocialCopyTab(e.detail.tab);
        }
        
        // Set a timeout to open the modal after the component is fully rendered
        setTimeout(() => {
          if (autoOpenSocialCopyRef.current) {
            setIsSocialCopyModalOpen(true);
            // Make sure button is scrolled into view
            if (socialCopyButtonRef.current) {
              socialCopyButtonRef.current.scrollIntoView({ behavior: 'smooth', block: 'center' });
            }
          }
        }, 300);
      }
    };

    // Add event listener
    document.addEventListener('openSocialCopyEditor', handleOpenSocialCopyEditor as EventListener);
    
    // Remove event listener on cleanup
    return () => {
      document.removeEventListener('openSocialCopyEditor', handleOpenSocialCopyEditor as EventListener);
    };
  }, [initialData?.id]);
  const [selectedTagIndex, setSelectedTagIndex] = useState(-1); // Track selected tag in dropdown
  const tagInputRef = useRef<HTMLInputElement>(null);
  const formRef = useRef<HTMLFormElement>(null);
  
  // Determine if the preview is autogenerated
  useEffect(() => {
    if (initialData) {
      // Check if preview is autogenerated based on card type and data
      if (type === 'reel' && initialData.preview) {
        // For reel cards, check explicitly if the metadata indicates it's auto-generated
        // or if the preview filename includes common auto-generated indicators
        const hasAutoGeneratedIndicator = 
          initialData.fileMetadata?.isPreviewGenerated === true ||
          (typeof initialData.preview === 'string' && (
            initialData.preview.includes('preview-fallback') ||
            initialData.preview.includes('auto-generated') ||
            initialData.preview.includes('-preview-')
          )) ||
          initialData.fileMetadata?.previewOriginalFileName?.includes('Auto-generated');
        
        
        setIsPreviewAutogenerated(hasAutoGeneratedIndicator || false);
      } else if (type === 'social' && initialData.preview && initialData.imageSequence && initialData.imageSequence.length > 0) {
        // For social cards, preview is auto-generated when it's the first image in the sequence
        const isFirstImage = initialData.preview === initialData.imageSequence[0];
        const isGenerated = isFirstImage || initialData.fileMetadata?.isPreviewGenerated === true;
        setIsPreviewAutogenerated(isGenerated);
      } else if (type === 'image' && initialData.preview && initialData.download) {
        // For image cards, preview is auto-generated when it matches the download image
        const isSameAsDownload = initialData.preview === initialData.download;
        const isGenerated = isSameAsDownload || initialData.fileMetadata?.isPreviewGenerated === true;
        setIsPreviewAutogenerated(isGenerated);
      } else {
        setIsPreviewAutogenerated(false);
      }
    } else {
      setIsPreviewAutogenerated(false);
    }
  }, [initialData, type]);

  // Effect to automatically open the social copy modal after the component mounts
  useEffect(() => {
    // Check if we have data in sessionStorage
    const storedData = sessionStorage.getItem('openSocialCopyEditor');
    let shouldOpenEditor = autoOpenSocialCopyRef.current;
    let editorTab = autoOpenSocialCopyTabRef.current;
    
    if (storedData) {
      try {
        const parsedData = JSON.parse(storedData);
        // Only use the stored data if it's recent (within the last 10 seconds) and matches this card
        const isRecent = Date.now() - parsedData.timestamp < 10000;
        if (isRecent && parsedData.cardId === initialData?.id) {
          shouldOpenEditor = true;
          editorTab = parsedData.tab || 'instagram';
          // Clear the storage to prevent reopening on page refresh
          sessionStorage.removeItem('openSocialCopyEditor');
        }
      } catch {
        // In case of parsing error, just clear the storage
        sessionStorage.removeItem('openSocialCopyEditor');
      }
    }
    
    // If we have any reason to open the editor, do it
    if (shouldOpenEditor && (type === 'social' || type === 'reel')) {
      // Add a slight delay to ensure the component is fully mounted
      setTimeout(() => {
        setIsSocialCopyModalOpen(true);
        setActiveSocialCopyTab(editorTab);
        // Scroll the button into view if it exists
        if (socialCopyButtonRef.current) {
          socialCopyButtonRef.current.scrollIntoView({ behavior: 'smooth', block: 'center' });
        }
      }, 500);
    }
  }, [initialData?.id, type]);

  // Connect the save button in the modal header to the form submit
  useEffect(() => {
    const saveButton = document.getElementById('modal-submit-button');
    const handleSaveClick = () => {
      if (formRef.current) {
        // If form is already submitting, don't trigger another submission
        if (isSubmitting) return;
        
        // Trigger form submission
        const submitEvent = new Event('submit', { cancelable: true, bubbles: true });
        formRef.current.dispatchEvent(submitEvent);
      }
    };

    if (saveButton) {
      saveButton.addEventListener('click', handleSaveClick);
      return () => {
        saveButton.removeEventListener('click', handleSaveClick);
      };
    }
  }, [isSubmitting]);
  
  // Handle modal close from backdrop or X button
  useEffect(() => {
    const modalBackdrop = document.getElementById('modal-backdrop');
    const closeButton = document.getElementById('modal-close-button');
    
    const handleCloseModal = () => {
      // Restore original image sequence
      setExistingImageSequence(originalImageSequence.current);
    };
    
    // Add click event listeners to the backdrop and close button
    if (modalBackdrop) {
      modalBackdrop.addEventListener('click', handleCloseModal);
    }
    
    if (closeButton) {
      closeButton.addEventListener('click', handleCloseModal);
    }
    
    // Clean up event listeners on unmount
    return () => {
      if (modalBackdrop) {
        modalBackdrop.removeEventListener('click', handleCloseModal);
      }
      
      if (closeButton) {
        closeButton.removeEventListener('click', handleCloseModal);
      }
    };
  }, []);

  // Fetch available tags if not provided
  useEffect(() => {
    const initializeTags = async () => {
      try {
        if (availableTags && availableTags.length > 0) {
          setAllAvailableTags(availableTags);
        } else {
          const tags = await getAllTags();
          setAllAvailableTags(tags);
        }
      } catch (error) {
        console.error('Error initializing tags:', error);
      }
    };

    initializeTags();
  }, [availableTags]);

  // Filter tags for dropdown - only show tags not already selected
  useEffect(() => {
    if (newTag.trim() === '') {
      // If no input but dropdown is open, show all available tags not already selected
      if (isTagsDropdownOpen) {
        const availableTags = [...allAvailableTags]
          .filter(tag => tag && !tags.includes(tag))
          .sort((a, b) => a.localeCompare(b));

        setFilteredTags(availableTags);
      } else {
        setFilteredTags([]);
      }
      return;
    }

    // Filter tags by prefix that aren't already selected
    const availableTags = allAvailableTags.filter(tag => tag && !tags.includes(tag));
    const input = newTag.toLowerCase().trim();
    const prefixMatches = availableTags
      .filter(tag => tag.toLowerCase().startsWith(input))
      .sort((a, b) => a.localeCompare(b));

    setFilteredTags(prefixMatches);
  }, [newTag, allAvailableTags, tags, isTagsDropdownOpen]);

  // Set up the required fields based on card type
  const getRequiredFields = () => {
    const common = ['description'];
    const typeSpecific = {
      image: ['download'],
      social: ['imageSequence'], // Now requires imageSequence instead of documentCopy
      reel: ['movie'], // Transcript is now optional for reel cards
    };

    return [...common, ...typeSpecific[type]];
  };

  const validateForm = () => {
    const requiredFields = getRequiredFields();
    const newErrors: Record<string, string> = {};
    
    if (!description.trim()) {
      newErrors.description = 'Description is required';
    }
    
    if (tags.length === 0) {
      newErrors.tags = 'At least one tag is required';
    }
    
    // Validate required files based on card type
    requiredFields.forEach(field => {
      if (field !== 'description') {
        if (field === 'imageSequence') {
          // For imageSequence, check if the array is empty
          const sequenceFiles = uploadedFiles[field] as File[];
          // Check both new and existing images
          const hasNewImages = sequenceFiles && sequenceFiles.length > 0;
          const hasExistingImages = existingImageSequence && existingImageSequence.length > 0;
          
          if (!hasNewImages && !hasExistingImages) {
            newErrors[field] = 'At least one image in the sequence is required';
          }
        } else if (!uploadedFiles[field] && !initialData?.[field as keyof CardProps]) {
          newErrors[field] = `${field.charAt(0).toUpperCase() + field.slice(1)} is required`;
        }
      }
    });
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleFileChange = (field: string) => (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      const file = e.target.files[0];

      // Check file size (max 500MB)
      const maxSize = 500 * 1024 * 1024; // 500MB
      if (file.size > maxSize) {
        setErrors(prev => ({
          ...prev,
          [field]: 'File size exceeds 500MB limit'
        }));
        return;
      }

      setUploadedFiles(prev => ({
        ...prev,
        [field]: file,
      }));

      // If this is a preview field, mark that this is a custom preview
      if (field === 'preview') {
        // When a user manually uploads a preview, it's no longer auto-generated
        setIsPreviewAutogenerated(false);
        
        // Clear the remove flag if it was set
        setUploadedFiles(prev => ({
          ...prev,
          remove_preview: false,
        }));
      }
      
      // For movie field in reel cards, mark any existing preview for regeneration
      if (field === 'movie' && type === 'reel') {
        // Always mark preview for removal when a new movie is uploaded
        // so that a new preview thumbnail will be generated
        setUploadedFiles(prev => ({
          ...prev,
          preview: null,
          remove_preview: true,
        }));
        setIsPreviewAutogenerated(true);
      }

      // If the field is a primary content that can generate a preview, 
      // automatically clear any existing preview unless it's a custom uploaded one
      if ((field === 'download' && type === 'image') || 
          (field === 'movie' && type === 'reel')) {
        
        // If the preview was autogenerated, silently mark it for removal
        if (isPreviewAutogenerated) {
          setUploadedFiles(prev => ({
            ...prev,
            preview: null,
            remove_preview: true,
          }));
        }
      }

      // Clear error for this field if it exists
      if (errors[field]) {
        setErrors(prev => {
          const newErrors = { ...prev };
          delete newErrors[field];
          return newErrors;
        });
      }
    }
  };

  const handleTagInput = (e: React.ChangeEvent<HTMLInputElement>) => {
    setNewTag(e.target.value);
    // Only show dropdown if there's input
    if (e.target.value.trim() !== '') {
      setIsTagsDropdownOpen(true);
    }
    // Reset selected index whenever input changes
    setSelectedTagIndex(-1);
  };

  const handleTagAdd = (tagToAdd?: string) => {
    // Important: If a tag is explicitly passed (from dropdown selection),
    // use it directly instead of using the current input value
    const tagValue = tagToAdd || newTag.trim();

    if (tagValue && !tags.includes(tagValue)) {
      const updatedTags = [...tags, tagValue];
      setTags(updatedTags);
      setNewTag('');
      setIsTagsDropdownOpen(false);

      // Clear tag error if it exists
      if (errors.tags) {
        setErrors(prev => {
          const newErrors = { ...prev };
          delete newErrors.tags;
          return newErrors;
        });
      }

      // Focus back on the input
      if (tagInputRef.current) {
        tagInputRef.current.focus();
      }
    }
  };

  const handleTagDelete = (tagToDelete: string) => {
    const updatedTags = tags.filter(tag => tag !== tagToDelete);
    setTags(updatedTags);
  };

  // Handle click outside of the dropdown to close it
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (tagInputRef.current && !tagInputRef.current.contains(event.target as Node)) {
        setIsTagsDropdownOpen(false);
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    // Double-check submission state to prevent multiple submissions
    if (!validateForm() || isSubmitting) {
      return;
    }

    // Dispatch event for the modal to show loading state
    document.dispatchEvent(new Event('form-submit-start'));

    try {
      const formData = new FormData();
      formData.append('type', type);
      formData.append('description', description);
      
      // Add flag to indicate if preview should be auto-generated
      if (isPreviewAutogenerated) {
        formData.append('generatePreview', 'true');
      }
      
      // Convert MM/DD/YYYY to YYYY-MM-DD for server storage
      try {
        if (date) {
          const parts = date.split('/');
          if (parts.length === 3) {
            const month = parts[0].padStart(2, '0');
            const day = parts[1].padStart(2, '0');
            const year = parts[2];
            // Store as YYYY-MM-DD for the server
            formData.append('date', `${year}-${month}-${day}`);
          } else {
            // Fallback if date is not in expected format
            formData.append('date', new Date().toISOString().split('T')[0]);
          }
        } else {
          // No date provided, use today
          formData.append('date', new Date().toISOString().split('T')[0]);
        }
      } catch (error) {
        console.error("Error formatting date for submission:", error);
        // Fallback to today's date
        formData.append('date', new Date().toISOString().split('T')[0]);
      }
      
      formData.append('tags', tags.join(','));
      
      // Append social copy if provided
      if (instagramCopy) {
        formData.append('instagramCopy', instagramCopy);
      }
      
      if (facebookCopy) {
        formData.append('facebookCopy', facebookCopy);
      }

      // Append files and removal flags
      Object.entries(uploadedFiles).forEach(([field, value]) => {

        if (field.startsWith('remove_') && value === true) {
          // Handle removal flags
          const actualField = field.replace('remove_', '');
          formData.append(`remove_${actualField}`, 'true');
        } else if (field === 'imageSequence' && Array.isArray(value)) {
          // Handle image sequence files
          value.forEach((file, index) => {
            formData.append(`imageSequence_${index}`, file);
          });
          // Add the count so the server knows how many files to process
          formData.append('imageSequenceCount', value.length.toString());
          
          // If this is an edit and we have existing images, add them to formData
          if (initialData && existingImageSequence.length > 0) {
            formData.append('existingImageSequence', JSON.stringify(existingImageSequence));
          }
        } else if (value instanceof File) {
          formData.append(field, value);
        }
      });

      await onSubmit(formData);
    } catch (error) {
      console.error('Error submitting form:', error);
      
      // Get the error message from the error
      let errorMessage = 'An error occurred while saving. Please try again.';
      if (error instanceof Error) {
        errorMessage = error.message;
      }
      
      setErrors(prev => ({
        ...prev,
        form: errorMessage,
      }));
      
      // Dispatch event for the modal to handle the error
      const errorEvent = new CustomEvent('form-submit-error', { 
        detail: errorMessage 
      });
      document.dispatchEvent(errorEvent);
      
      // Also dispatch the normal end event to hide loading state
      document.dispatchEvent(new Event('form-submit-end'));
    } finally {
      // This ensures the loading state is always cleared
      setTimeout(() => {
        document.dispatchEvent(new Event('form-submit-end'));
      }, 500);
    }
  };

  const handleRemoveFile = (field: string) => () => {

    // First set the field to null
    setUploadedFiles(prev => {
      return {
        ...prev,
        [field]: null,
      };
    });

    // Then, in a separate update, set the remove flag
    // This needs to be done for all existing files, not just preview
    if (initialData?.[field as keyof CardProps]) {
      setUploadedFiles(prev => {
        const result = {
          ...prev,
          [`remove_${field}`]: true,
        };
        return result;
      });
    }

    // If this is a preview being removed, mark it as autogenerated
    // so that a new preview will be generated from the source
    if (field === 'preview') {
      setIsPreviewAutogenerated(true);
      
      // Also ensure we set the generatePreview flag to true
      // This is needed so the server knows to generate a new preview
      setUploadedFiles(prev => ({
        ...prev,
        generatePreview: true
      }));
    }

    // Clear any errors for this field
    if (errors[field]) {
      setErrors(prev => {
        const newErrors = { ...prev };
        delete newErrors[field];
        return newErrors;
      });
    }
  };

  const handleFileInputClick = (fieldId: string) => (e: React.MouseEvent) => {
    // Prevent default button behavior
    e.preventDefault();
    // Programmatically click the hidden file input
    document.getElementById(fieldId)?.click();
  };

  const renderFileInput = (field: string, label: string, accept?: string, isOptional: boolean = false) => {
    // We don't need special handling for reel previews anymore
    // All auto-generated previews will be handled in the main rendering flow
    
    const hasSelectedFile = uploadedFiles[field] instanceof File;
    const selectedFileName = hasSelectedFile ? (uploadedFiles[field] as File).name : '';
    const fileInputId = `${field}-input`;

    return (
      <div className="mb-4">
        <div className
="font-medium mb-1 text-sm">
          {field === 'preview' ? 'Preview Image' : field === 'movie' ? 'Video File' : label.replace('Preview ', '').replace('Downloadable ', '').replace('Thumbnail ', '').replace('Video ', '').replace('Document ', '')} {isOptional && <span className="text-gray-500 text-xs">(Optional)</span>}
          {field === 'preview' && type === 'social' && (
            <div className="text-xs text-gray-500 mt-1">
              If not provided, the first image in the sequence will be used as preview.
            </div>
          )}
          {field === 'preview' && type === 'image' && (
            <div className="text-xs text-gray-500 mt-1">
              If not provided, the image will be used.
            </div>
          )}
          {field === 'preview' && type === 'reel' && (
            <div className="text-xs text-gray-500 mt-1">
              If not provided, a thumbnail from the video will be auto-generated.
            </div>
          )}
        </div>
        <div className="flex flex-col">
          {/* Hidden file input for native file dialog */}
          <input
            id={fileInputId}
            type="file"
            onChange={handleFileChange(field)}
            accept={accept || "*/*"}
            multiple={false}
            className="hidden" // Hide the native input
          />

          {/* Custom file input UI with drag-and-drop */}
          <div 
            className={`flex flex-col items-stretch rounded p-2 border border-gray-200 border-dashed transition-all ${isSubmitting ? 'opacity-50 pointer-events-none' : ''}`}
            onDragOver={(e) => {
              e.preventDefault();
              e.stopPropagation();
              // Add drag over styling to the target
              e.currentTarget.classList.add('bg-blue-50', 'border-blue-300', 'border-2');
            }}
            onDragLeave={(e) => {
              e.preventDefault();
              e.stopPropagation();
              // Remove drag over styling
              e.currentTarget.classList.remove('bg-blue-50', 'border-blue-300', 'border-2');
            }}
            onDrop={(e) => {
              e.preventDefault();
              e.stopPropagation();
              
              // Remove drag over styling
              e.currentTarget.classList.remove('bg-blue-50', 'border-blue-300', 'border-2');
              
              if (isSubmitting) return;
              
              // Get the dropped files
              const files = Array.from(e.dataTransfer.files);
              if (files.length === 0) return;
              
              // Use the first file
              const file = files[0];
              
              // Check if the accept pattern matches
              if (accept) {
                const acceptTypes = accept.split(',').map(type => type.trim());
                const fileType = file.type;
                
                // Check if the file type matches any accept pattern
                const isAccepted = acceptTypes.some(acceptType => {
                  if (acceptType.endsWith('/*')) {
                    // Handle wildcard MIME types (e.g., 'image/*')
                    const mainType = acceptType.split('/')[0];
                    return fileType.startsWith(mainType + '/');
                  }
                  return acceptType === fileType;
                });
                
                if (!isAccepted) {
                  alert(`File type not accepted. Please upload ${accept} files.`);
                  return;
                }
              }
              
              // Manually set the uploaded files
              setUploadedFiles(prev => ({
                ...prev,
                [field]: file,
              }));
              
              // Handle preview auto-generation for video uploads
              if (field === 'movie' && type === 'reel') {
                setUploadedFiles(prev => ({
                  ...prev,
                  preview: null,
                  remove_preview: true,
                }));
                setIsPreviewAutogenerated(true);
              }
              
              // Clear error for this field if it exists
              if (errors[field]) {
                setErrors(prev => {
                  const newErrors = { ...prev };
                  delete newErrors[field];
                  return newErrors;
                });
              }
            }}
          >
            <div className="flex items-center py-1">
              <button
                type="button"
                onClick={isSubmitting ? undefined : handleFileInputClick(fileInputId)}
                className={`px-3 py-1.5 bg-blue-50 border border-blue-200 rounded flex items-center gap-1 ${isSubmitting ? 'opacity-50 cursor-not-allowed' : 'hover:bg-blue-100 transition-colors'}`}
                disabled={isSubmitting}
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 text-blue-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" />
                </svg>
                <span>Browse Files</span>
              </button>
              <span className="mx-3 text-gray-500 text-sm">or</span>
              <div className="flex items-center text-blue-600">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M9 19l3 3m0 0l3-3m-3 3V10" />
                </svg>
                <span className="text-sm font-medium">Drop File Here</span>
              </div>
            </div>

            {hasSelectedFile ? (
              <div className="mt-2 flex items-center gap-2 bg-blue-50 px-2 py-1 rounded text-xs">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 text-blue-500 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
                <span className="text-blue-600 font-medium truncate">
                  {selectedFileName}
                </span>
                <button
                  type="button"
                  onClick={isSubmitting ? undefined : handleRemoveFile(field)}
                  className={`text-red-500 ml-auto flex-shrink-0 ${isSubmitting ? 'opacity-50 cursor-not-allowed' : 'hover:text-red-700'}`}
                  title="Remove file"
                  disabled={isSubmitting}
                >
                  ✕
                </button>
              </div>
            ) : uploadedFiles[`remove_${field}`] === true ? (
              // Show removed state when a file has been marked for removal
              <div className="mt-2 flex items-center gap-2 bg-red-50 px-2 py-1 rounded text-xs">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 text-red-500 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                </svg>
                <span className="text-red-600 italic truncate">
                  (File will be removed)
                </span>
                <button
                  type="button"
                  onClick={() => {
                    // Allow undoing the removal
                    setUploadedFiles(prev => ({
                      ...prev,
                      [`remove_${field}`]: false
                    }));
                  }}
                  className="text-blue-500 hover:text-blue-700 ml-auto flex-shrink-0"
                  title="Undo removal"
                >
                  ↺
                </button>
              </div>
            ) : (
              initialData && initialData[field as keyof CardProps] && (
                <div className="mt-2 flex items-center gap-2 bg-blue-50 px-2 py-1 rounded text-xs">
                  {/* For non-autogenerated files, show the filename and delete button */}
                  {!(field === 'preview' && isPreviewAutogenerated) ? (
                    <>
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 text-blue-500 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                      </svg>
                      <span className="text-blue-600 font-medium truncate">
                        {initialData.fileMetadata && initialData.fileMetadata[`${field}OriginalFileName` as keyof typeof initialData.fileMetadata] ?
                          initialData.fileMetadata[`${field}OriginalFileName` as keyof typeof initialData.fileMetadata] as string :
                          typeof initialData[field as keyof CardProps] === 'string' ?
                            (initialData[field as keyof CardProps] as string).split('/').pop() :
                            'File'
                        }
                      </span>
                      {/* Only show delete button for non-autogenerated files */}
                      {(isOptional || !initialData) && (
                        <button
                          type="button"
                          onClick={handleRemoveFile(field)}
                          className="text-red-500 hover:text-red-700 ml-auto flex-shrink-0"
                          title="Remove file"
                        >
                          ✕
                        </button>
                      )}
                    </>
                  ) : (
                    /* For autogenerated previews, just show (Auto Generated) with no delete button */
                    <>
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 text-green-500 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                      <span className="text-green-600 font-medium truncate">
                        (Auto Generated)
                      </span>
                    </>
                  )}
                </div>
              )
            )}
          </div>

          <small className="text-gray-500 mt-1 text-xs">
            {field.includes('preview') || field.includes('download') ?
              'Supported formats: jpg, jpeg, png, gif, webp, svg' :
              field.includes('movie') || field.includes('video') ?
                'Supported formats: mp4, mov, avi, webm (up to 500MB)' :
                field === 'transcript' ?
                  'Supported formats: txt, srt, pdf, docx, Pages, Google Docs - For transcriptions, subtitles, or dialogue text' :
                  'Supported formats: pdf, txt, doc, docx, srt'
            }
          </small>
        </div>
        {errors[field] && (
          <div className="mt-1 text-sm text-red-500">
            {errors[field]}
          </div>
        )}
      </div>
    );
  };

  // We've removed the specialized renderReelPreview function as we're now handling all auto-generated previews consistently

  // Create ref outside the render function
  const socialCopyButtonRef = useRef<HTMLButtonElement>(null);
  
  // Helper to render social copy button
  const renderSocialCopyButton = () => {
    const hasSocialCopy = instagramCopy || facebookCopy;
    
    const handleOpenModal = () => {
      // First ensure the button is in view
      if (socialCopyButtonRef.current) {
        socialCopyButtonRef.current.scrollIntoView({ behavior: 'smooth', block: 'center' });
        
        // Then open the modal after scrolling completes
        setTimeout(() => {
          setIsSocialCopyModalOpen(true);
        }, 300);
      } else {
        setIsSocialCopyModalOpen(true);
      }
    };
    
    return (
      <div className="mb-4">
        <div className="font-medium mb-1 text-sm">Social Media Copy <span className="text-gray-500 text-xs">(Optional)</span></div>
        <button
          ref={socialCopyButtonRef}
          type="button"
          onClick={handleOpenModal}
          disabled={isSubmitting}
          className={`px-4 py-2 ${hasSocialCopy ? 'bg-blue-50 border border-blue-200' : 'bg-gray-50 border border-gray-200'} rounded flex items-center gap-2 ${isSubmitting ? 'opacity-50 cursor-not-allowed' : 'hover:bg-blue-100 transition-colors'}`}
        >
          <svg xmlns="http://www.w3.org/2000/svg" className={`h-4 w-4 ${hasSocialCopy ? 'text-blue-600' : 'text-gray-600'}`} viewBox="0 0 20 20" fill="currentColor">
            <path d="M17.414 2.586a2 2 0 00-2.828 0L7 10.172V13h2.828l7.586-7.586a2 2 0 000-2.828z" />
            <path fillRule="evenodd" d="M2 6a2 2 0 012-2h4a1 1 0 010 2H4v10h10v-4a1 1 0 112 0v4a2 2 0 01-2 2H4a2 2 0 01-2-2V6z" clipRule="evenodd" />
          </svg>
          <span>{hasSocialCopy ? 'Edit Social Copy' : 'Add Social Copy'}</span>
        </button>
        {hasSocialCopy && (
          <div className="mt-2">
            <div className="text-xs text-gray-500">
              {instagramCopy && <div>✓ Instagram Copy</div>}
              {facebookCopy && <div>✓ Facebook Copy</div>}
            </div>
          </div>
        )}
      </div>
    );
  };

  const renderCardTypeFields = () => {
    switch (type) {
      case 'image':
        return (
          <>
            {renderFileInput('download', 'Downloadable Image', 'image/*,.jpg,.jpeg,.png,.gif,.webp,.svg')}
            {renderFileInput('preview', 'Preview Image', 'image/*,.jpg,.jpeg,.png,.gif,.webp,.svg', true)}
          </>
        );
      case 'social':
        return (
          <>
            <MultiImageUploader 
              initialImages={existingImageSequence}
              onChange={(files) => {
                setUploadedFiles(prev => ({
                  ...prev,
                  imageSequence: files
                }));
                
                // If the first image is changing and preview was autogenerated,
                // silently mark it for removal so a new preview will be generated
                if (type === 'social' && 
                    files.length > 0 && 
                    isPreviewAutogenerated) {
                  setUploadedFiles(prev => ({
                    ...prev,
                    preview: null,
                    remove_preview: true,
                  }));
                }
                
                // Clear any errors
                if (errors.imageSequence) {
                  setErrors(prev => {
                    const newErrors = { ...prev };
                    delete newErrors.imageSequence;
                    return newErrors;
                  });
                }
              }}
              onExistingImagesChange={(urls) => {
                setExistingImageSequence(urls);
                
                // If the sequence has changed and preview was autogenerated,
                // mark it for removal so it can be regenerated
                if (type === 'social' && 
                    (!initialData?.imageSequence || 
                     initialData.imageSequence[0] !== urls[0]) && 
                    isPreviewAutogenerated) {
                  setUploadedFiles(prev => ({
                    ...prev,
                    preview: null,
                    remove_preview: true,
                  }));
                }
              }}
              isSubmitting={isSubmitting}
            />
            {errors.imageSequence && (
              <div className="mt-1 text-sm text-red-500">
                {errors.imageSequence}
              </div>
            )}
            {renderSocialCopyButton()}
            {renderFileInput('preview', 'Preview Image', 'image/*,.jpg,.jpeg,.png,.gif,.webp,.svg', true)}
            {renderFileInput('transcript', 'Transcript/Subtitles (optional)', 'application/pdf,text/plain,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.apple.pages,application/vnd.google-apps.document,.txt,.pdf,.srt,.docx,.pages,.gdoc', true)}
          </>
        );
      case 'reel':
        return (
          <>
            {renderFileInput('movie', 'Video File', 'video/*,.mp4,.mov,.avi,.webm')}
            {renderSocialCopyButton()}
            {renderFileInput('preview', 'Preview Image', 'image/*,.jpg,.jpeg,.png,.gif,.webp,.svg', true)}
            {renderFileInput('transcript', 'Transcript', 'application/pdf,text/plain,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.apple.pages,application/vnd.google-apps.document,.txt,.pdf,.srt,.docx,.pages,.gdoc', true)}
          </>
        );
      default:
        return null;
    }
  };

  return (
    <div>
      {errors.form && (
        <div className="mb-4 p-4 bg-red-50 border border-red-400 text-red-700 rounded">
          {errors.form}
        </div>
      )}
      
      <form ref={formRef} onSubmit={handleSubmit}>
        <div className="mb-4">
          <h3 className="text-base font-medium mb-2">Card Type</h3>
          {initialData ? (
            // For editing existing cards, just show the type
            <div className="text-gray-700 py-1 font-medium">
              {TYPE_LABELS[type as keyof typeof TYPE_LABELS]}
            </div>
          ) : (
            // For new cards, show radio buttons only if initialCardType is 'all' (undefined)
            initialCardType === 'all' ? (
              <>
                <div className="flex gap-4">
                  {Object.entries(TYPE_LABELS).map(([typeValue, label]) => (
                    <label 
                      key={typeValue} 
                      className="flex items-center cursor-pointer"
                    >
                      <input
                        type="radio"
                        name="cardType"
                        value={typeValue}
                        checked={type === typeValue}
                        onChange={() => {
                          // Reset the form state when changing type
                          // Ensure the typeValue is one of the allowed values
                          if (typeValue === 'image' || typeValue === 'social' || typeValue === 'reel') {
                            setType(typeValue);
                            setUploadedFiles({});
                            setErrors({});
                          }
                        }}
                        className="mr-2"
                        disabled={isSubmitting}
                      />
                      {label}
                    </label>
                  ))}
                </div>
                <p className="text-xs text-gray-500 mt-1">Card type is fixed and cannot be changed after creation</p>
              </>
            ) : (
              // For new cards with a specific type, just show the type
              <div className="text-gray-700 py-1">
                {TYPE_LABELS[type as keyof typeof TYPE_LABELS]}
              </div>
            )
          )}
        </div>
        
        <div className="mb-4">
          <label className="block text-sm font-medium mb-1" htmlFor="description">
            Description
          </label>
          <textarea
            id="description"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            className={`w-full px-3 py-2 border rounded text-sm ${errors.description ? 'border-red-500' : 'border-gray-300'} ${isSubmitting ? 'opacity-70 cursor-not-allowed' : ''}`}
            rows={3}
            disabled={isSubmitting}
          />
          {errors.description && (
            <div className="mt-1 text-sm text-red-500">
              {errors.description}
            </div>
          )}
        </div>

        <div className="mb-4">
          <label className="block text-sm font-medium mb-1" htmlFor="date">
            Date
          </label>
          <input
            type="text"
            id="date"
            value={date}
            onChange={(e) => {
              // Store raw input
              setDate(e.target.value);
              // Mark date as modified for Enter key handling
              setIsDateModified(true);
            }}
            onKeyDown={(e) => {
              if (e.key === 'Enter') {
                e.preventDefault(); // Prevent form submission
                
                if (isDateModified) {
                  // Parse and format the date
                  const formattedDate = parseAndFormatDate(date);
                  setDate(formattedDate);
                  setIsDateModified(false);
                } else {
                  // If date hasn't been modified, submit the form
                  formRef.current?.dispatchEvent(
                    new Event('submit', { cancelable: true, bubbles: true })
                  );
                }
              }
            }}
            onBlur={() => {
              // On blur, parse the date and reformat if valid
              if (isDateModified) {
                const formattedDate = parseAndFormatDate(date);
                setDate(formattedDate);
                setIsDateModified(false);
              }
            }}
            className={`w-full px-3 py-2 border border-gray-300 rounded text-sm ${isSubmitting ? 'opacity-70 cursor-not-allowed' : ''}`}
            disabled={isSubmitting}
            placeholder="MM/DD/YYYY"
          />
          <p className="text-xs text-gray-500 mt-1">
            Enter Date MM/DD/YYYY
          </p>
        </div>
        
        <div className="mb-4">
          <h3 className="text-base font-medium mb-2">Tags</h3>
          <div className="relative">
            <div className="flex mb-2">
              <div className="relative w-full">
                <div className="relative flex items-center">
                  <input
                    ref={tagInputRef}
                    type="text"
                    value={newTag}
                    onChange={handleTagInput}
                    placeholder="Type to search or add a new tag"
                    className={`w-full mr-2 px-3 py-2 pr-10 border border-gray-300 rounded text-sm ${isSubmitting ? 'opacity-70 cursor-not-allowed' : ''}`}
                    disabled={isSubmitting}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter') {
                        e.preventDefault();

                        // If a tag is selected in the dropdown, use that one
                        if (isTagsDropdownOpen && selectedTagIndex >= 0 && selectedTagIndex < filteredTags.length) {
                          handleTagAdd(filteredTags[selectedTagIndex]);
                        }
                        // If dropdown is open and has suggestions but none selected, use the first one
                        else if (isTagsDropdownOpen && filteredTags.length > 0) {
                          handleTagAdd(filteredTags[0]);
                        } else {
                          // Otherwise use current input
                          handleTagAdd();
                        }
                      } else if (e.key === 'Escape') {
                        setIsTagsDropdownOpen(false);
                      } else if (e.key === 'ArrowDown' && filteredTags.length > 0 && isTagsDropdownOpen) {
                        e.preventDefault();
                        // Move to the next item or first item if none selected
                        setSelectedTagIndex(prev =>
                          prev < filteredTags.length - 1 ? prev + 1 : 0
                        );
                      } else if (e.key === 'ArrowUp' && filteredTags.length > 0 && isTagsDropdownOpen) {
                        e.preventDefault();
                        // Move to the previous item or last item if at beginning
                        setSelectedTagIndex(prev =>
                          prev > 0 ? prev - 1 : filteredTags.length - 1
                        );
                      }
                    }}
                    onFocus={() => {
                      // Do not show dropdown when focusing
                    }}
                    autoComplete="off" // Prevent browser autocomplete from interfering
                  />
                  <button
                    type="button"
                    onClick={() => {
                      if (!isSubmitting) {
                        setIsTagsDropdownOpen(!isTagsDropdownOpen);
                        if (tagInputRef.current) {
                          tagInputRef.current.focus();
                        }
                      }
                    }}
                    className={`absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400 p-1 rounded ${isSubmitting ? 'opacity-50 cursor-not-allowed' : 'hover:text-gray-600 hover:bg-gray-100'}`}
                    aria-label={isTagsDropdownOpen ? "Close tag options" : "Show tag options"}
                    disabled={isSubmitting}
                  >
                    <svg 
                      xmlns="http://www.w3.org/2000/svg" 
                      width="16" 
                      height="16" 
                      viewBox="0 0 24 24" 
                      fill="none" 
                      stroke="currentColor" 
                      strokeWidth="2" 
                      strokeLinecap="round" 
                      strokeLinejoin="round"
                      className={`transition-transform duration-200 ${isTagsDropdownOpen ? 'rotate-180' : ''}`}
                    >
                      <polyline points="6 9 12 15 18 9"></polyline>
                    </svg>
                  </button>
                  {isTagsDropdownOpen && (
                    <div
                      id="tags-dropdown"
                      className="absolute z-10 mt-1 w-full bg-white border border-gray-200 rounded-md shadow-lg max-h-60 overflow-y-auto"
                    >
                      {filteredTags.length > 0 ? (
                        filteredTags.map((tag, index) => {
                          // Only highlight the prefix (since we're only doing prefix matching)
                          const lowerInput = newTag.toLowerCase().trim();
                          const isSelected = index === selectedTagIndex;

                          let tagDisplay;
                          if (lowerInput.length > 0) {
                            // Highlight just the prefix that matches
                            const prefixLength = lowerInput.length;
                            const prefix = tag.substring(0, prefixLength);
                            const rest = tag.substring(prefixLength);

                            tagDisplay = (
                              <>
                                <span className="font-bold text-blue-600">{prefix}</span>
                                {rest}
                              </>
                            );
                          } else {
                            tagDisplay = tag;
                          }

                          return (
                            <button
                              key={tag}
                              type="button"
                              onClick={() => handleTagAdd(tag)}
                              className={`w-full text-left px-3 py-2 text-sm hover:bg-blue-50 focus:bg-blue-50 focus:outline-none ${isSelected ? 'bg-blue-100 font-medium' : ''}`}
                              tabIndex={0}
                              onMouseEnter={() => setSelectedTagIndex(index)}
                            >
                              {tagDisplay}
                            </button>
                          );
                        })
                      ) : (
                        newTag.length > 0 ? (
                          <div className="px-3 py-2 text-sm flex">
                            <span className="text-blue-600 font-medium">{newTag}</span>
                            <span className="text-gray-500 ml-1">(Press Enter to add)</span>
                          </div>
                        ) : (
                          <div className="px-3 py-2 text-sm text-gray-500">
                            No matching tags found
                          </div>
                        )
                      )}
                    </div>
                  )}
                </div>
              </div>
              <button
                type="button"
                onClick={() => {
                  // If there's a selected tag in the dropdown, use that
                  if (isTagsDropdownOpen && selectedTagIndex >= 0 && selectedTagIndex < filteredTags.length) {
                    handleTagAdd(filteredTags[selectedTagIndex]);
                  } 
                  // If dropdown is open with suggestions but none selected, use first one
                  else if (isTagsDropdownOpen && filteredTags.length > 0) {
                    handleTagAdd(filteredTags[0]);
                  } 
                  // Otherwise use whatever is in the input
                  else {
                    handleTagAdd();
                  }
                }}
                className={`px-3 py-2 bg-blue-600 text-white rounded text-sm whitespace-nowrap ${isSubmitting ? 'opacity-50 cursor-not-allowed' : 'hover:bg-blue-700'}`}
                disabled={isSubmitting}
              >
                Add Tag
              </button>
            </div>
          </div>

          <div className="flex flex-wrap gap-2 mt-2">
            {tags.map((tag) => (
              <span
                key={tag}
                className="inline-flex items-center px-2 py-1 rounded text-xs bg-blue-100 text-blue-800"
              >
                {tag}
                <button
                  type="button"
                  onClick={() => !isSubmitting && handleTagDelete(tag)}
                  className={`ml-1.5 text-blue-600 ${isSubmitting ? 'opacity-50 cursor-not-allowed' : 'hover:text-blue-800'}`}
                  disabled={isSubmitting}
                >
                  &times;
                </button>
              </span>
            ))}
          </div>

          {errors.tags && (
            <div className="mt-1 text-sm text-red-500">
              {errors.tags}
            </div>
          )}

          {tags.length === 0 && (
            <p className="text-xs text-gray-500 mt-1">Add at least one tag to categorize this card</p>
          )}
        </div>

        {renderCardTypeFields()}

        <div className="flex justify-end gap-3 mt-6">
          <button
            type="button"
            onClick={() => {
              // Restore original image sequence before canceling
              setExistingImageSequence(originalImageSequence.current);
              onCancel();
            }}
            disabled={isSubmitting}
            className={`px-4 py-2 border border-gray-300 text-gray-700 rounded ${isSubmitting ? 'opacity-50 cursor-not-allowed' : 'hover:bg-gray-50'}`}
          >
            Cancel
          </button>
          <button
            type="submit"
            disabled={isSubmitting}
            className={`px-4 py-2 bg-blue-600 text-white rounded ${isSubmitting ? 'opacity-50 cursor-not-allowed' : 'hover:bg-blue-700'}`}
          >
            {isSubmitting ? 'Saving...' : (initialData ? 'Update' : 'Create')}
          </button>
        </div>
      </form>
      
      {/* Social Copy Modal */}
      <SocialCopyModal
        isOpen={isSocialCopyModalOpen}
        onClose={() => setIsSocialCopyModalOpen(false)}
        onSave={(instagram, facebook) => {
          setInstagramCopy(instagram);
          setFacebookCopy(facebook);
          setIsSocialCopyModalOpen(false);
        }}
        initialInstagramCopy={instagramCopy}
        initialFacebookCopy={facebookCopy}
        initialActiveTab={activeSocialCopyTab}
      />
    </div>
  );
};

export default CardFormNew;
